queue pull consumer (Work in progress)
ReubenMathew/nats-k8s-burn-in-testing pull request #3
Opened 2023-02-24 01:55 UTC by ReubenMathew

Finds an error:
```
2023/02/23 20:46:51 Received #20298 by Subscriber-17
2023/02/23 20:46:51 Published #20299
2023/02/23 20:46:51 Received #20299 by Subscriber-22
2023/02/23 20:46:51 Published #20300
2023/02/23 20:46:51 Received #20300 by Subscriber-19
2023/02/23 20:46:51 Published #20301
2023/02/23 20:46:51 Received #8116 by Subscriber-22
2023/02/23 20:46:51 Test failed: Expected 20301 but received 8116 by Subscriber-22
exit status 1
❌ Test failed
```

2023-02-24 17:30 UTC, ReubenMathew commented on tests/queue-pull-consumer.go
> +				msg.Ack()
check `ack` error

2023-02-24 20:37 UTC, ReubenMathew commented on tests/queue-pull-consumer.go
> +				msg.Ack()
Fixed in [b049dff](https://github.com/ReubenMathew/nats-k8s-burn-in-testing/pull/3/commits/b049dff0422b5c206c7c9122c83099a1cce3aab0)

2023-02-24 23:39 UTC, mprimi requested changes

2023-02-24 23:39 UTC, mprimi commented on tests/queue-pull-consumer.go
> +			nc.QueueSubscribe(DeliverSubjectName, DeliverGroupName, func(msg *nats.Msg) {
Notice all clients are sharing a connection, so they're all connected to the same server.
To make it a bit more realistic/hard different consumers should have different connections (so they're connected to different servers)

2023-02-24 23:39 UTC, mprimi commented on tests/queue-pull-consumer.go
> +					log.Println("Data format error %w", err)
This should panic, or at least error out and fail the test

2023-02-24 23:39 UTC, mprimi commented on tests/queue-pull-consumer.go
> +			currentData := <-content
If no consumer delivers the message, the main thread gets stuck here forever. 

You can solve by putting this into a `select` block with a timeout

2023-02-24 23:39 UTC, mprimi commented on tests/queue-pull-consumer.go
> +						return
Returning here just kills this goroutine

2023-02-24 23:42 UTC, mprimi commented
Also please add test description to README

2023-02-25 00:52 UTC, ReubenMathew commented on tests/queue-pull-consumer.go
> +						return
Do we need a case for the experiment timer in the individual routines? Won't the main loop's case just kill the forked processes anyway?

2023-02-27 17:48 UTC, mprimi commented on tests/queue-pull-consumer.go
> +			nc.QueueSubscribe(DeliverSubjectName, DeliverGroupName, func(msg *nats.Msg) {
Check for error

2023-02-27 22:11 UTC, mprimi requested changes
Very minor changes

2023-02-27 22:11 UTC, mprimi commented on tests/queue-group-consumer.go
> +			continue mainRunLoop
Could print some stats here to show messages are being processed

2023-02-27 22:11 UTC, mprimi commented on tests/queue-group-consumer.go
> +				return fmt.Errorf("Experiment timed before receiving expected message with sequence number: %d", prevSeqNumber)
If the 'experiment' timer runs out right after publishing, the test may fail, even if nothing was wrong.
Should probably just return nil here.

2023-02-27 22:11 UTC, mprimi commented on README.md
> +The test consists of
... creates N queue subscribers (each using a different connection).

Instead of the first snipped of pseudocode below, which is just setup.

2023-02-27 22:11 UTC, mprimi commented on README.md
> +for j in M {
i / j

2023-02-27 23:36 UTC, ReubenMathew commented
@mprimi implemented your suggestions, its ready for another look.

2023-02-27 23:39 UTC, mprimi commented
@ReubenMathew LGTM, you should squash

2023-02-27 23:43 UTC, merged